package model;
// Generated Apr 15, 2018 12:33:11 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotBlank;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Nhanvien generated by hbm2java
 */
@Entity

@Table(name="nhanvien"
    ,catalog="quanlythanhtichabc"
)
public class Nhanvien  implements java.io.Serializable {

    
     private String manv;
     
     private Phongban phongban;

     private String hoten;
       
     private String gioitinh;
       

     private Date ngaysinh;

     private int luong;
 
     private int capdo;
     private String loaitk;
     

     private String email;

     private String dienthoai;
     private String password;
     private Set<Thanhtichkyluat> ttkl = new HashSet<Thanhtichkyluat>(5);
     private String tenhinh;
     private Date ngaygiothem;
     
@Temporal(TemporalType.DATE)
    @Column(name="thoigianthem", length=10)
    public Date getNgaygiothem() {
        return this.ngaygiothem;
    }
    
    public void setNgaygiothem(Date ngaygiothem) {
        this.ngaygiothem = ngaygiothem;
    }
   
    
     
    public Nhanvien() {
    }

    public Nhanvien(String manv, String hoten, String gioitinh  , Date ngaysinh, int luong, int capdo, String loaitk, String email, String dienthoai, String password, String tenhinh) {
        this.manv = manv;
        this.hoten = hoten;
        this.gioitinh = gioitinh;
         
        this.ngaysinh = ngaysinh;
        this.luong = luong;
        this.capdo = capdo;
        this.loaitk = loaitk;
        this.email = email;
        this.dienthoai = dienthoai;
        this.password = password;
        this.tenhinh = tenhinh;
    
    }

    public Nhanvien(String manv, Phongban phongban, String hoten, String gioitinh  , Date ngaysinh, int luong, int capdo, String loaitk, String email, String dienthoai, String password,  Set<Thanhtichkyluat> ttkl, String tenhinh) {
        this.manv = manv;
        this.phongban = phongban;
        this.hoten = hoten;
        this.gioitinh = gioitinh;
         
        this.ngaysinh = ngaysinh;
        this.luong = luong;
        this.capdo = capdo;
        this.loaitk = loaitk;
        this.email = email;
        this.dienthoai = dienthoai;
        this.password = password;
  
        this.ttkl = ttkl;
        this.tenhinh = tenhinh;
       
    }

	
    
   
     @Id 
    @Column(name="manv", unique=true, nullable=false, length=5)
    public String getManv() {
        return this.manv;
    }
    
    public void setManv(String manv) {
        this.manv = manv;
    }

@ManyToOne(fetch=FetchType.LAZY,cascade = { CascadeType.MERGE, CascadeType.PERSIST} )
    @JoinColumn(name="maphongban")
    public Phongban getPhongban() {
        return this.phongban;
    }
    
    public void setPhongban(Phongban phongban) {
        this.phongban = phongban;
    }

  
    @Column(name="hoten", length=500)
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }

    
    @Column(name="gioitinh", length=4)
    public String getGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }
 @Column(name="loaitk", length=2)
    public String getLoaitk() {
        return loaitk;
    }

    public void setLoaitk(String loaitk) {
        this.loaitk = loaitk;
    }

   
   

    @Temporal(TemporalType.DATE)
    @Column(name="ngaysinh", length=10)
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    public Date getNgaysinh() {
        return this.ngaysinh;
    }
    
    public void setNgaysinh(Date ngaysinh) {
        this.ngaysinh = ngaysinh;
    }

    
    @Column(name="luong")
    public int getLuong() {
        return this.luong;
    }
    
    public void setLuong(int luong) {
        this.luong = luong;
    }

    
    @Column(name="capdo")
    public int getCapdo() {
        return this.capdo;
    }
    
    public void setCapdo(int capdo) {
        this.capdo = capdo;
    }
@Column(name="tenhinh", length=200)
    public String getTenhinh() {
        return tenhinh;
    }

    public void setTenhinh(String tenhinh) {
        this.tenhinh = tenhinh;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="dienthoai", length=11)
    public String getDienthoai() {
        return this.dienthoai;
    }
    
    public void setDienthoai(String dienthoai) {
        this.dienthoai = dienthoai;
    }

    
    @Column(name="password", length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="nhanvien")
    public Set<Thanhtichkyluat> getThanhtichkyluat() {
        return this.ttkl;
    }
    
    public void setThanhtichkyluat(Set<Thanhtichkyluat> thanhtichkyluat) {
        this.ttkl = thanhtichkyluat;
    }




}


