package model;
// Generated Apr 15, 2018 12:33:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Formula;

/**
 * Phongban generated by hbm2java
 */
@Entity
@Table(name="phongban"
    ,catalog="quanlythanhtichabc"
)
public class Phongban  implements java.io.Serializable {


     private String maphong;
     private String tenphong;
     private Set<Nhanvien> nhanviens = new HashSet<Nhanvien>(10);
     private Set<Thanhtichkyluat> thanhtichs = new HashSet<Thanhtichkyluat>(10);
     private int demgd;
       private int demkt;
       private int demns;
       private int sonv;
       
       
       
       


    public void setDemgd(int demgd) {
        this.demgd = demgd;
    }
      


     @Formula("(select count(*) from nhanvien)")
    public int getSonv() {
        return sonv;
    }

    public void setSonv(int sonv) {
        this.sonv = sonv;
    }
    
   
    

    
    
    
    public Phongban() {
    }

	
    public Phongban(String maphong, String tenphong) {
        this.maphong = maphong;
        this.tenphong = tenphong;
        
    }
    public Phongban(String maphong, String tenphong, Set<Nhanvien> nhanviens, Set<Thanhtichkyluat> thanhtichs) {
       this.maphong = maphong;
       this.tenphong = tenphong;
       this.thanhtichs = thanhtichs;
       this.nhanviens = nhanviens;
   
    }
   
     @Id 

    
    @Column(name="maphong", unique=true, nullable=false, length=2)
    public String getMaphong() {
        return this.maphong;
    }
    
    public void setMaphong(String maphong) {
        this.maphong = maphong;
    }

    
    @Column(name="tenphong", length=100)
    public String getTenphong() {
        return this.tenphong;
    }
    
    public void setTenphong(String tenphong) {
        this.tenphong = tenphong;
    }

    
 

@OneToMany(fetch=FetchType.LAZY, mappedBy="phongban",cascade={CascadeType.ALL})
    public Set<Nhanvien> getNhanviens() {
        return this.nhanviens;
    }
    
    public void setNhanviens(Set<Nhanvien> nhanviens) {
        this.nhanviens = nhanviens;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="phongban",cascade={CascadeType.ALL})
    public Set<Thanhtichkyluat> getThanhtichs() {
        return thanhtichs;
    }

    public void setThanhtichs(Set<Thanhtichkyluat> thanhtichs) {
        this.thanhtichs = thanhtichs;
    }






}


